apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-skaffold
spec:
  selector:
    matchLabels:
      app: rails-skaffold
  replicas: 2
  template:
    metadata:
      labels:
        app: rails-skaffold
    spec:
      containers:
      - name: rails-skaffold
        image: rails-skaffold
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: puma
spec:
  type: NodePort
  selector:
    app: rails-skaffold
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 3000
      targetPort: 3000
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 32222
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-skaffold
spec:
  selector:
    matchLabels:
      app: postgres-skaffold
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-skaffold
    spec:
      containers:
      - name: postgres-skaffold
        image: postgres:9.6.18
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres-skaffold
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-setup
spec:
  template:
    spec:
      containers:
      - name: db-setup
        image: rails-skaffold
        command: ["/bin/sh", "-c"]
        args:
        - sleep 5;
          bundle exec rake db:create;
          bundle exec rake db:migrate;
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: batch/v1
kind: Job
metadata:
  name: tests
spec:
  template:
    spec:
      containers:
      - name: tests
        image: rails-skaffold
        command: ["/bin/sh", "-c"]
        args:
        - sleep 5;
          bundle exec rspec;
      restartPolicy: Never
  backoffLimit: 4
