apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-skaffold
spec:
  selector:
    matchLabels:
      app: rails-skaffold
  replicas: 2
  template:
    metadata:
      labels:
        app: rails-skaffold
    spec:
      containers:
      - name: rails-skaffold
        image: rails-skaffold
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: puma
spec:
  type: NodePort
  selector:
    app: rails-skaffold
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 3000
      targetPort: 3000
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 32222
