apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: rails-skaffold
build:
  local:
    push: false
  artifacts:
  - image: rails-skaffold
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s-manifest.yml
