name: CI using Skaffold

on: push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install kubectl and skaffold
        uses: yokawasa/action-setup-kube-tools@v0.3.0
        with:
          kubectl: '1.17.1'
        id: setup
      - name: Build and deploy to cluster
        run: skaffold run
