name: CI using Skaffold

on: push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install kubectl
        uses: yokawasa/action-setup-kube-tools@v0.3.0
        with:
          kubectl: '1.20.0'
        id: setup
      - name: Install skaffold
        uses: daisaru11/setup-cd-tools@v1
        with:
          skaffold: '1.20.0'
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
