name: CI using Skaffold

on: push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install kubectl
        uses: yokawasa/action-setup-kube-tools@v0.3.0
        with:
          kubectl: '1.20.0'
        id: setup
      - name: Install skaffold
        uses: daisaru11/setup-cd-tools@v1
        with:
          skaffold: '1.20.0'
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - name: Authenticate with Docker registry
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Run skaffold
        run: |
          skaffold config set default-repo tarrynn/rails-skaffold
          skaffold run
