name: CI using Skaffold

on: push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install kubectl and skaffold
        uses: daisaru11/setup-cd-tools@v1
        with:
          kubectl: '1.20.4'
          skaffold: '1.20.0'
      - name: Build and deploy to cluster
        run: skaffold run
