name: CI using Skaffold

on: push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install kubectl
        uses: yokawasa/action-setup-kube-tools@v0.3.0
        with:
          kubectl: '1.20.0'
        id: setup
      - name: Run Skaffold pipeline
        uses: hiberbee/github-action-skaffold@latest
        with:
          command: run
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
